### ISSUE TITLE
config doesn't seems to be applied 

### ISSUE THREAD

**Issue by bliveinhack** [MarcinOrlowski/laravel-api-response-builder#149] opened 2020-08-20 14:03 UTC
**What's wrong?**
I have just installed and publish config.

Now when i simply use

    return ResponseBuilder::success(UserType::all(),200);

it gives me response like 

```
{
  "success": true,
  "code": 200,
  "locale": "en",
  "message": "OK",
  "data": {
    "0": {
      "id": 1,
      "description": "User",
      "slug": "USER",
      "created_at": "2020-07-17 22:31:49",
      "updated_at": "2020-07-17 22:31:49"
    },
    "1": {
      "id": 2,
      "description": "Sales",
      "slug": "OTHER_USER",
      "created_at": "2020-07-17 22:31:49",
      "updated_at": "2020-07-17 22:31:49"
    }
  }
}
```

**Steps to reproduce the behavior:**
1.  just install fresh stable version 8.0
2.  run vendor publish.
3.  use ResponseBuilder::success() with collection

**Expected behavior**
it should use data converter applied in project and give collection data output without preserving keys...

**Runtime environment**
 - Name and version of OS: Windows 10
 - PHP version 7.4.*
 - Laravel version 6.*

**Notes**

**Comment by MarcinOrlowski** [comment] 2020-09-17 08:53
I suspect that for some reasons invalid converter is being used on your collection. To check that, please update Response Builder to v8.1.0 and enable converter debug logs (i.e. by adding `RB_CONVERTER_DEBUG=true` to your `.env` file). Then see the logs.

**Comment by MarcinOrlowski** [comment] 2020-10-15 19:20
I finally manage to reproduce this so it seems like a RB's bug.

**Comment by MarcinOrlowski** [comment] 2020-10-15 19:44
Ok, so this is not really a bug per se. By design, the `data` node is always an object, therefore if you want to return an array, you should give it an extra key to avoid output as you shown. This is documented in [https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/docs/examples.md](usage examples). The trick here is that you are passing `Collection` which is then autoconverted to `array` and then returned, so technically this is exactly that case. In current version you would need to return like this:

    RB::success(['my_key' => $collection]);

which would work around that. But I do agree this is ugly. I will think about better approach for next release.

**Comment by MarcinOrlowski** [comment] 2020-10-15 19:52
I am closing this ticket as this is not a bug. There's #158 created, please subscribe to it to be informed about further development.

**Closed by MarcinOrlowski** 2020-10-15 19:52 UTC
Labels: bug

**Comment by MarcinOrlowski** [comment] 2020-10-16 10:37
For a record, ths is now implemented as part of `dev` branch and will appear in v9 shortly.
