### ISSUE TITLE
unauthenticed() is never called when using ExceptionHandler with Laravel 5.3+

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#37] opened 2017-02-25 04:26 UTC
Inside the exception handler render I have:

```
return ExceptionHandlerHelper::render($request, $e);
```

Just below that the unauthenticed function is never called

```
/**
     * Convert an authentication exception into an unauthenticated response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Auth\AuthenticationException  $exception
     * @return \Illuminate\Http\Response
     */
    protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        }
        return redirect()->guest(route('login'));
    }
```

So if I want the unauthenticed to be called I have to remove the ExceptionHandlerHelper. Is this by design?

I know why because the parent::render() function checks for exceptions https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L113 your exception handler doesn't use the unauthenticated so it throws 500 internal error instead of a 401.

**Comment by MarcinOrlowski** [comment] 2017-02-25 19:44
What version of Laravel you use?

**Comment by dragonfire1119** [comment] 2017-02-25 19:54
@MarcinOrlowski Laravel 5.3 & 5.4.

**Comment by MarcinOrlowski** [comment] 2017-02-27 10:49
I checked the framework code and lack of invocation of `unauthenticated()` in my handler simply not supported at the moment. It is definitely NOT a feature nor done by design. `unauthenticated()` is introduced in Laravel 5.3 and I apparently missed this so current ExceptionHandler needs to be fixed to have this supported.

**Comment by dragonfire1119** [comment] 2017-02-27 19:07
@MarcinOrlowski Oh ok well we're all humans so we can always miss something! LOL. I figured it wasn't by design but had to ask...

**Comment by MarcinOrlowski** [comment] 2017-04-08 09:16
Can you checkout version from this branch:
https://github.com/MarcinOrlowski/laravel-api-response-builder/tree/rb-37-unauthenticated and try?

**Comment by MarcinOrlowski** [comment] 2017-04-08 11:16
Fixed in @dev

**Closed by MarcinOrlowski** 2017-04-08 11:16 UTC
Labels: bug
